cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'node'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'unrar'
brew 'wget'
brew 'python'
brew 'git'
brew 'python3'
brew 'fzf'
brew 'hub'
brew 'mongodb'
brew 'zsh-syntax-highlighting'
brew 'z'

cask '1password'
cask 'garmin-express'
cask 'google-chrome'
cask 'slack'
cask 'transmission'
cask 'vlc'
cask 'sublime-text'
cask 'docker'
cask 'sequel-pro'
cask 'virtualbox'
cask 'vagrant'
cask 'spotify'
cask 'dropbox'
cask 'iterm2'
cask 'spectacle'